# Generated by Django 6.0.7 on 2026-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Портал групи', max_length=100, verbose_name='Назва порталу')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Фонове зображення')),
                ('overlay_opacity', models.PositiveIntegerField(default=55, help_text='0 — фон без затемнення, 100 — повністю чорний. Впливає на читабельність тексту.', verbose_name='Затемнення фону (%)')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
