# Generated by Django 6.0.7 on 2026-08-02 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва роботи')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/', verbose_name='Файл/матеріал')),
                ('link', models.URLField(blank=True, verbose_name='Посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Робота портфоліо',
                'verbose_name_plural': 'Портфоліо',
                'ordering': ['-created_at'],
            },
        ),
    ]
